#!/usr/bin/python3
#SPDX-FileCopyrightText: 2022 Takumi Ohtake s20c1025ng@s.chibakoudai.jp 
#SPDX-License-Identifier: BSD-3-Clause

import sys
import re



x = 0
for n in sys.stdin:
    try:
        x += int(n)
    except:
        x += float(n)

print(x)
